### ISSUE TITLE
#Bugfix - Only show username with rootguy

### ISSUE THREAD

**Issue by lesoname** [lesoname/blog#53]
![image](https://user-images.githubusercontent.com/105822034/202616717-6b39422c-6afa-4b2a-bd43-fd01057f09e5.png)

![image](https://user-images.githubusercontent.com/105822034/202616750-fbe17eee-3e3e-4b57-94a4-0ca01efcf84e.png)

**Comment by lesoname** [comment]
![image](https://user-images.githubusercontent.com/105822034/202617239-6b786d44-266b-40e4-abd9-82df48b98e96.png)

username is a "nill". The form don't receive the username argument

**Comment by lesoname** [comment]
https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address

Look this^

**Comment by ttMath** [comment]
In the new branch this bug has been fixed


pleasecheck this banch > https://github.com/lesoname/blog/pull/55

**Comment by ttMath** [comment]
![Screenshot from 2022-11-18 18-04-09](https://user-images.githubusercontent.com/96507218/202804490-e93ad676-66c6-4870-ab23-333e6406f137.png)



Username is being registered now
